### ISSUE TITLE
A little glich, nothing really important

### ISSUE THREAD

**Issue by ghost** [lastweakness/Komikku#4]
Hello friend, i'am loving the new app. 
I noticed a little glich after closing the menu in window mode, it only happens in a couple of window dimensions. I'am using the latest flatpak version.

![Captura de tela de 2021-09-30 21-39-22](https://user-images.githubusercontent.com/62822515/135549716-db63f3ec-85c4-44c2-90ef-f3bf28715b77.png)

BTW, the aplication name in brazilian portuguese means "buthole eater".  LOL

Best regards,
Vitor

**Comment by mufeedali** [comment]
You meant to open this issue here: https://www.gitlab.com/valos/Komikku :)

**Comment by ghost** [comment]
Yeah, sorry about that.

**Comment by mufeedali** [comment]
No worries XD
